Testing ktlint

diff --git a/.github/workflows/ktlint.yml b/.github/workflows/ktlint.yml
--- a/.github/workflows/ktlint.yml
+++ b/.github/workflows/ktlint.yml
@@ -20,11 +20,12 @@ jobs:
         run: chmod +x ./gradlew
 
       - name: Run Ktlint
-        run: ./gradlew ktlintCheck || true
-
-      - name: Validate Ktlint
-        run: |
-          if grep -q '.*Error.*' build/reports/ktlint/ktlintMainCheck.txt; then
-            echo "Ktlint detected linting errors."
-            exit 1
-          fi
+        run: ./gradlew ktlintCheck
+#          || true
+#
+#      - name: Validate Ktlint
+#        run: |
+#          if grep -q '.*Error.*' build/reports/ktlint/ktlintMainCheck.txt; then
+#            echo "Ktlint detected linting errors."
+#            exit 1
+#          fi
